export const APP_CONFIG = {
  MAX_TITLE_LENGTH: 100,
  NOTES_KEY: 'NOTES',
  CATEGORIES_KEY: 'CATEGORIES',
  DEBOUNCE_DELAY: 500,
  REFRESH_THRESHOLD: 500,
};

export const STORAGE_KEYS = {
  NOTES: 'NOTES',
  CATEGORIES: 'CATEGORIES',
};
